spring.application.name=cloud-compliance-service

spring.datasource.url=jdbc:mariadb://localhost:3306/ccs
spring.datasource.username=root
spring.datasource.password=hema@2003
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true